name: slinky_view
description: A sheet that aligns to the bottom of a widget and expands as scroll up.
version: 1.1.0
homepage: https://github.com/idonuntius/slinky_view

environment:
  sdk: ">=2.18.4 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
